import { chromium } from "playwright";
const OUT = "/private/tmp/claude-501/-Users-gigic-Downloads-revived-smiles-main/667838ce-d43d-4f28-a363-dc25f27360d0/scratchpad";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 430, height: 1000 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto("http://localhost:3000/care-guide", { waitUntil: "networkidle" });
await page.getByRole("heading", { name: "Care Guide" }).waitFor({ timeout: 10000 });
await page.getByText("Clean it daily").waitFor({ timeout: 5000 });
await page.screenshot({ path: `${OUT}/cg-icon.png` });
await browser.close();
console.log("OK");
